refactor!: rewrite UI handling
ZakShearman/mc-tower-defence pull request #77
Opened 2024-01-07 15:04 UTC by LooFifteen

2024-01-08 23:37 UTC, LooFifteen commented on src/main/java/pink/zak/minestom/towerdefence/ui/spawner/TroopSpawnerUI.java
> +                    items.add(currentlyTrackedMob.getLevel(this.gameUser.getMobLevels().get(currentlyTrackedMob)).createPreviewItem().withAmount(count));
Creating an item each iteration probably isn't a great idea, should probably count the number of mobs beforehand.

2024-01-08 23:37 UTC, LooFifteen commented on src/main/java/pink/zak/minestom/towerdefence/ui/spawner/TroopSpawnerUI.java
> +    }
Since queues are player-specific, this update can be called inside the inventory as the queue will only be updated after interacting with it.

2024-01-08 23:37 UTC, LooFifteen commented on src/main/java/pink/zak/minestom/towerdefence/ui/spawner/TroopUpgradeTab.java
> +        }
This code reads like hell, is there a better way of writing it?

2024-01-08 23:37 UTC, LooFifteen commented on src/main/java/pink/zak/minestom/towerdefence/ui/spawner/TroopUpgradeTab.java
> +        this.gameUser.getMobLevels().put(this.mob, clickedLevel);
There should probably be some sort of upgrade handler rather than it being handled in UI.

2024-01-08 23:37 UTC, LooFifteen commented on src/main/java/pink/zak/minestom/towerdefence/ui/spawner/TroopSpawnerUI.java
> +    }
This should definitely be handled elsewhere.

2024-01-08 23:37 UTC, LooFifteen commented on src/main/java/pink/zak/minestom/towerdefence/ui/spawner/TroopSpawnerUI.java
> +        if (level == null) return; // the player attempted to send a mob that they don't own
There should be better feedback for cases like these, e.g. a sound.

2024-01-08 23:37 UTC, LooFifteen commented on src/main/java/pink/zak/minestom/towerdefence/ui/spawner/TroopSpawnerUI.java
> +            Integer userLevel = levels.get(enemyMob);
Sorry, is that a boxed integer???

2024-01-08 23:37 UTC, LooFifteen commented on src/main/java/pink/zak/minestom/towerdefence/ui/spawner/TroopUpgradeTab.java
> +        this.parent.updateSubInventory();
Is there a way to get the parent to listen for updates rather than it relying on the child to trigger it?

2024-01-08 23:37 UTC, LooFifteen commented on src/main/java/pink/zak/minestom/towerdefence/ui/spawner/TroopUpgradeTab.java
> +    }
This could be a part of the mob level class, rather than in here.

2024-01-09 15:26 UTC, LooFifteen commented on src/main/java/pink/zak/minestom/towerdefence/ui/spawner/TroopSpawnerUI.java
> +    }
This cannot be done as the queue updates itself, maybe an event can be used instead?

2024-01-09 15:27 UTC, LooFifteen commented on src/main/java/pink/zak/minestom/towerdefence/ui/spawner/TroopSpawnerUI.java
> +            Integer userLevel = levels.get(enemyMob);
The level is nullable lol..

2024-01-09 15:30 UTC, LooFifteen commented on src/main/java/pink/zak/minestom/towerdefence/ui/spawner/TroopUpgradeTab.java
> +    }
Enemy levels are unaware of their parent mob, so this isn't possible.

2024-01-11 19:16 UTC, LooFifteen commented on src/main/java/pink/zak/minestom/towerdefence/ui/spawner/TroopUpgradeTab.java
> +        this.parent.updateSubInventory();
This is probably the best way of doing it.

2024-01-11 23:08 UTC, ZakShearman commented
Startyed doing a review then realised I should probably bug test first.

Bugs:
- Current Queue in the mob GUI doesn't immediately update, have you made it schedule updating now?
- Upgrade troops GUI has all the mobs from the previous GUI chilling there.

I'll also submit a half completed review coz I might as well.

2024-01-11 23:16 UTC, LooFifteen commented
> Upgrade troops GUI has all the mobs from the previous GUI chilling there.
What is the intended behaviour?

2024-01-11 23:30 UTC, LooFifteen commented on src/main/java/pink/zak/minestom/towerdefence/queue/MobQueue.java
> +    }
The mob is removed from the queue at the start of their spawn timer. This means the mob is technically no longer in the queue way before it even spawns. It should probably be removed from the queue after it has spawned.

2024-01-11 23:32 UTC, LooFifteen commented on src/main/java/pink/zak/minestom/towerdefence/queue/MobQueue.java
> +    }
This does not seem to be the case when testing.. must be too late in the evening.

2024-01-11 23:36 UTC, ZakShearman commented
Bugs before I leave a review:

- In the upgrade menu, when you click to upgrade a mob it still shows all the others mobs. If you meant this, it just looks confusing with them smushed up against each other.
- Should be a back button in the upgrade menu. This was just never added before but should be now.

2024-01-11 23:39 UTC, LooFifteen commented
I think the upgrade menu should be overhauled. Would it be a better idea to:
* Get into a mob's upgrade menu by right-clicking it.
* Have a back button in the bottom-right-hand corner.

2024-01-11 23:42 UTC, ZakShearman commented
You probably should be able to get into upgrade by right clicking but ALSO a button to get into it.

The intended behaviour what it was before - it doesn't show the other troops. Keeping the other troops there makes the GUI extremely dense and hard to understand from a UX perspective.

It might work if there is spacing between all the mobs and the upgrading section.

2024-01-11 23:44 UTC, LooFifteen commented on src/main/java/pink/zak/minestom/towerdefence/ui/spawner/TroopSpawnerUI.java
>              }
Wondering the intention for this change? Doing this will direct clicks to the outer UI rather than the inner when the clicked item is air.

2024-01-11 23:48 UTC, LooFifteen commented
> but ALSO a button to get into it

Having a separate upgrading UI that looks *identical* to the spawning UI is very confusing in my opinion.

2024-01-11 23:50 UTC, ZakShearman commented
> Having a separate upgrading UI that looks _identical_ to the spawning UI is very confusing in my op

Hmm maybe yh. get rid of the intermediary GUI then yh.

2024-01-12 10:58 UTC, LooFifteen commented
fixed 👍🏼

2024-01-12 21:42 UTC, ZakShearman commented
New GUI looks good - only things:

We probably need a system to cancel an 'instant buy' of a mob (right click to unlock). Maybe if a user hasn't sent the mob yet and they've unlocked it in the past 10 seconds they can SHIFT + RCLICK to sell back that unlock.

We need to display the cost of unlocking a mob on that instant buy right click to unlock.

2024-01-13 00:00 UTC, ZakShearman requested changes

2024-01-13 11:02 UTC, LooFifteen commented on src/main/java/pink/zak/minestom/towerdefence/ui/UserSettingsUI.java
> +            if (!p.equals(player)) return;
`player` is already defined in the constructor scope by its parameters.

2024-01-13 11:04 UTC, LooFifteen commented on src/main/java/pink/zak/minestom/towerdefence/ui/spawner/TroopUpgradeUI.java
> +        if (clickedLevel < 0) return;
damn you're right

2024-01-13 11:05 UTC, LooFifteen commented on src/main/java/pink/zak/minestom/towerdefence/ui/tower/TowerManagementUI.java
> +    @ApiStatus.Internal
Forgot to remove this, it had a reason but doesn't any more.

2024-01-13 11:08 UTC, LooFifteen commented on src/main/java/pink/zak/minestom/towerdefence/ui/tower/TowerManagementUI.java
> +        Set<SendablePacket> packets = clickType == ClickType.LEFT_CLICK ? createRadiusPackets(this.tower, Collections.emptySet()) : new HashSet<>();
It's a static method as it doesn't require any object data. Should I move it into the object?

2024-01-13 11:08 UTC, LooFifteen commented on src/main/java/pink/zak/minestom/towerdefence/ui/tower/TowerManagementUI.java
> +                packets.addAll(createRadiusPackets(tower, otherTowers));
See https://github.com/ZakShearman/mc-tower-defence/pull/77#discussion_r1451456409

2024-01-13 11:56 UTC, LooFifteen commented
`TowerManager#determineDirection` needs to be looked at/rewritten.

2024-01-13 12:53 UTC, ZakShearman commented on src/main/java/pink/zak/minestom/towerdefence/ui/tower/TowerManagementUI.java
> +        Set<SendablePacket> packets = clickType == ClickType.LEFT_CLICK ? createRadiusPackets(this.tower, Collections.emptySet()) : new HashSet<>();
ngl i remember checking it was a static method and going ok yes. I then must've come back to it and done an oopsie lol

2024-01-18 00:08 UTC, ZakShearman approved these changes

2024-01-18 00:10 UTC, merged